# Generated by Django 4.2.19 on 2025-03-03 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=100, verbose_name='Название альбома')),
                ('album_duration', models.DurationField(verbose_name='Продолжительность альбома')),
                ('album_release_date', models.DateField(blank=True, verbose_name='Дата релиза')),
            ],
            options={
                'verbose_name': 'альбом',
                'verbose_name_plural': 'Альбом',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='Название исполнителя(ей)')),
                ('author_birthday', models.DateField(blank=True, verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name': 'исполнитель',
                'verbose_name_plural': 'Исполнитель',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=56, verbose_name='Название страны')),
            ],
            options={
                'verbose_name': 'страна',
                'verbose_name_plural': 'Страна',
            },
        ),
        migrations.CreateModel(
            name='FormatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20, verbose_name='Название типа')),
            ],
            options={
                'verbose_name': 'тип',
                'verbose_name_plural': 'Тип',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=50, verbose_name='Название жанра')),
                ('user_genre_favors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'жанр',
                'verbose_name_plural': 'Жанр',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=100, verbose_name='Название песни')),
                ('song_duration', models.DurationField(verbose_name='Продолжительность песни')),
                ('song_release_date', models.DateField(blank=True, verbose_name='Дата релиза')),
                ('author', models.ManyToManyField(to='Collections.author')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Collections.country', verbose_name='Страна')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Collections.genre', verbose_name='Жанр')),
                ('song_album', models.ManyToManyField(to='Collections.album')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Collections.formattype', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'песня',
                'verbose_name_plural': 'Песня',
            },
        ),
        migrations.CreateModel(
            name='playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.CharField(max_length=150, verbose_name='Название плейлиста')),
                ('playlist_create_date', models.DateField(verbose_name='Дата создания')),
                ('playlist_description', models.TextField(blank=True, max_length=500, verbose_name='Описание плейлиста')),
                ('playlist_cover', models.ImageField(upload_to='', verbose_name='Изображение для плейлиста')),
                ('playlist_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('song', models.ManyToManyField(to='Collections.song')),
            ],
            options={
                'verbose_name': 'плейлист',
                'verbose_name_plural': 'Плейлисты',
            },
        ),
        migrations.AddField(
            model_name='author',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='Collections.country', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='album',
            name='author',
            field=models.ManyToManyField(to='Collections.author'),
        ),
        migrations.AddField(
            model_name='album',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Collections.country', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Collections.genre', verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='album',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Collections.formattype', verbose_name='Тип'),
        ),
    ]
