# Generated by Django 4.2.19 on 2025-03-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Описание'),
        ),
    ]
