# Generated by Django 4.2.19 on 2025-03-03 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=150, verbose_name='Заголовок новости')),
                ('news_text', models.TextField(max_length=1000, verbose_name='Текст новости')),
                ('news_publiting_date', models.DateField(auto_now=True, verbose_name='Дата публикации')),
                ('news_img', models.ImageField(upload_to='', verbose_name='Изображение новости')),
                ('news_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'Новость',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(max_length=500, verbose_name='Комментарий')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='Homepage.news', verbose_name='Новость')),
                ('user_comment_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'Комментарий',
            },
        ),
    ]
